/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTyreSetupRouteImport } from './routes/_authenticated/tyre-setup'
import { Route as AuthenticatedTiresRouteImport } from './routes/_authenticated/tires'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGarageRouteImport } from './routes/_authenticated/garage'
import { Route as AuthenticatedFlagsRouteImport } from './routes/_authenticated/flags'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCalculatorsRouteImport } from './routes/_authenticated/calculators'
import { Route as AuthenticatedBaselineRouteImport } from './routes/_authenticated/baseline'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as ShareSessionTokenRouteImport } from './routes/share.session.$token'
import { Route as AuthenticatedSetupsSetupIdRouteImport } from './routes/_authenticated/setups.$setupId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedCarsCarIdRouteImport } from './routes/_authenticated/cars.$carId'
import { Route as AuthenticatedSessionsSessionIdPitboardRouteImport } from './routes/_authenticated/sessions.$sessionId.pitboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTyreSetupRoute = AuthenticatedTyreSetupRouteImport.update({
  id: '/tyre-setup',
  path: '/tyre-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiresRoute = AuthenticatedTiresRouteImport.update({
  id: '/tires',
  path: '/tires',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarageRoute = AuthenticatedGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlagsRoute = AuthenticatedFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalculatorsRoute =
  AuthenticatedCalculatorsRouteImport.update({
    id: '/calculators',
    path: '/calculators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBaselineRoute = AuthenticatedBaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShareSessionTokenRoute = ShareSessionTokenRouteImport.update({
  id: '/share/session/$token',
  path: '/share/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupsSetupIdRoute =
  AuthenticatedSetupsSetupIdRouteImport.update({
    id: '/setups/$setupId',
    path: '/setups/$setupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedCarsCarIdRoute = AuthenticatedCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsSessionIdPitboardRoute =
  AuthenticatedSessionsSessionIdPitboardRouteImport.update({
    id: '/pitboard',
    path: '/pitboard',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/baseline': typeof AuthenticatedBaselineRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/tires': typeof AuthenticatedTiresRoute
  '/tyre-setup': typeof AuthenticatedTyreSetupRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/setups/$setupId': typeof AuthenticatedSetupsSetupIdRoute
  '/share/session/$token': typeof ShareSessionTokenRoute
  '/sessions/$sessionId/pitboard': typeof AuthenticatedSessionsSessionIdPitboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/baseline': typeof AuthenticatedBaselineRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/tires': typeof AuthenticatedTiresRoute
  '/tyre-setup': typeof AuthenticatedTyreSetupRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/setups/$setupId': typeof AuthenticatedSetupsSetupIdRoute
  '/share/session/$token': typeof ShareSessionTokenRoute
  '/sessions/$sessionId/pitboard': typeof AuthenticatedSessionsSessionIdPitboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/baseline': typeof AuthenticatedBaselineRoute
  '/_authenticated/calculators': typeof AuthenticatedCalculatorsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/flags': typeof AuthenticatedFlagsRoute
  '/_authenticated/garage': typeof AuthenticatedGarageRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/tires': typeof AuthenticatedTiresRoute
  '/_authenticated/tyre-setup': typeof AuthenticatedTyreSetupRoute
  '/_authenticated/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/_authenticated/setups/$setupId': typeof AuthenticatedSetupsSetupIdRoute
  '/share/session/$token': typeof ShareSessionTokenRoute
  '/_authenticated/sessions/$sessionId/pitboard': typeof AuthenticatedSessionsSessionIdPitboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analysis'
    | '/baseline'
    | '/calculators'
    | '/calendar'
    | '/expenses'
    | '/flags'
    | '/garage'
    | '/inventory'
    | '/maintenance'
    | '/notes'
    | '/sessions'
    | '/tires'
    | '/tyre-setup'
    | '/cars/$carId'
    | '/sessions/$sessionId'
    | '/setups/$setupId'
    | '/share/session/$token'
    | '/sessions/$sessionId/pitboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analysis'
    | '/baseline'
    | '/calculators'
    | '/calendar'
    | '/expenses'
    | '/flags'
    | '/garage'
    | '/inventory'
    | '/maintenance'
    | '/notes'
    | '/sessions'
    | '/tires'
    | '/tyre-setup'
    | '/cars/$carId'
    | '/sessions/$sessionId'
    | '/setups/$setupId'
    | '/share/session/$token'
    | '/sessions/$sessionId/pitboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analysis'
    | '/_authenticated/baseline'
    | '/_authenticated/calculators'
    | '/_authenticated/calendar'
    | '/_authenticated/expenses'
    | '/_authenticated/flags'
    | '/_authenticated/garage'
    | '/_authenticated/inventory'
    | '/_authenticated/maintenance'
    | '/_authenticated/notes'
    | '/_authenticated/sessions'
    | '/_authenticated/tires'
    | '/_authenticated/tyre-setup'
    | '/_authenticated/cars/$carId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/setups/$setupId'
    | '/share/session/$token'
    | '/_authenticated/sessions/$sessionId/pitboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShareSessionTokenRoute: typeof ShareSessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tyre-setup': {
      id: '/_authenticated/tyre-setup'
      path: '/tyre-setup'
      fullPath: '/tyre-setup'
      preLoaderRoute: typeof AuthenticatedTyreSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tires': {
      id: '/_authenticated/tires'
      path: '/tires'
      fullPath: '/tires'
      preLoaderRoute: typeof AuthenticatedTiresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garage': {
      id: '/_authenticated/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AuthenticatedGarageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flags': {
      id: '/_authenticated/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AuthenticatedFlagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calculators': {
      id: '/_authenticated/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AuthenticatedCalculatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/baseline': {
      id: '/_authenticated/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof AuthenticatedBaselineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/session/$token': {
      id: '/share/session/$token'
      path: '/share/session/$token'
      fullPath: '/share/session/$token'
      preLoaderRoute: typeof ShareSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setups/$setupId': {
      id: '/_authenticated/setups/$setupId'
      path: '/setups/$setupId'
      fullPath: '/setups/$setupId'
      preLoaderRoute: typeof AuthenticatedSetupsSetupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/cars/$carId': {
      id: '/_authenticated/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthenticatedCarsCarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$sessionId/pitboard': {
      id: '/_authenticated/sessions/$sessionId/pitboard'
      path: '/pitboard'
      fullPath: '/sessions/$sessionId/pitboard'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdPitboardRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedSessionsSessionIdRouteChildren {
  AuthenticatedSessionsSessionIdPitboardRoute: typeof AuthenticatedSessionsSessionIdPitboardRoute
}

const AuthenticatedSessionsSessionIdRouteChildren: AuthenticatedSessionsSessionIdRouteChildren =
  {
    AuthenticatedSessionsSessionIdPitboardRoute:
      AuthenticatedSessionsSessionIdPitboardRoute,
  }

const AuthenticatedSessionsSessionIdRouteWithChildren =
  AuthenticatedSessionsSessionIdRoute._addFileChildren(
    AuthenticatedSessionsSessionIdRouteChildren,
  )

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRouteWithChildren
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsSessionIdRoute:
    AuthenticatedSessionsSessionIdRouteWithChildren,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedBaselineRoute: typeof AuthenticatedBaselineRoute
  AuthenticatedCalculatorsRoute: typeof AuthenticatedCalculatorsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFlagsRoute: typeof AuthenticatedFlagsRoute
  AuthenticatedGarageRoute: typeof AuthenticatedGarageRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedTiresRoute: typeof AuthenticatedTiresRoute
  AuthenticatedTyreSetupRoute: typeof AuthenticatedTyreSetupRoute
  AuthenticatedCarsCarIdRoute: typeof AuthenticatedCarsCarIdRoute
  AuthenticatedSetupsSetupIdRoute: typeof AuthenticatedSetupsSetupIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedBaselineRoute: AuthenticatedBaselineRoute,
  AuthenticatedCalculatorsRoute: AuthenticatedCalculatorsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFlagsRoute: AuthenticatedFlagsRoute,
  AuthenticatedGarageRoute: AuthenticatedGarageRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedTiresRoute: AuthenticatedTiresRoute,
  AuthenticatedTyreSetupRoute: AuthenticatedTyreSetupRoute,
  AuthenticatedCarsCarIdRoute: AuthenticatedCarsCarIdRoute,
  AuthenticatedSetupsSetupIdRoute: AuthenticatedSetupsSetupIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShareSessionTokenRoute: ShareSessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
